apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodportal
spec:
  selector:
    matchLabels:
      app: foodportal
  replicas: 1
  template:
    metadata:
      labels:
        app: foodportal
    spec:
       hostname: foodportal
       hostAliases:
       - ip: "127.0.9.1"
         hostnames:
          - "latavola"
       - ip: "127.0.9.2"
         hostnames:
          - "pizzaboyz"
       - ip: "127.0.9.3"
         hostnames:
          - "sidepizza"
       containers:
        - image: clemensv.azurecr.io/foodportal
          name: foodportal
          ports:
            - containerPort: 80
        - image: clemensv.azurecr.io/azbridge
          name: azbridge
          env:
          - name: RELAYCXN
            valueFrom:
              secretKeyRef:
                name: relaycxn
                key: cxn
          args: ["-L","latavola:8000/http:latavola", "-L","pizzaboyz:8000/http:pizzaboyz", "-L","sidepizza:8000/http:sidepizza", "-x","'$(RELAYCXN)'"] 
       imagePullSecrets:
        - name: clemensv.azurecr.io