apiVersion: v1
kind: Service
metadata:
  name: foodportal
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
  selector:
    app: foodportal
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foodportal
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: foodportal-lb.c6a2bf9d95e04a74a300.westus.aksapp.io
      http:
        paths:
          - backend:
              service:
                 name: foodportal
                 port: 
                   number: 80
            path: /
            pathType: Prefix
