apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "FoodPortal.fullname" . }}
  labels:
    {{- include "FoodPortal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "FoodPortal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "FoodPortal.selectorLabels" . | nindent 8 }}
    spec:  
      hostname: foodportal
      hostAliases:
       - ip: "127.0.9.1"
         hostnames:
          - "latavola"
       - ip: "127.0.9.2"
         hostnames:
          - "pizzaboyz"
       - ip: "127.0.9.3"
         hostnames:
          - "sidepizza"
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "FoodPortal.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: azbridge
          image: "{{ .Values.azbridgeimage.repository }}"
          imagePullPolicy: {{ .Values.azbridgeimage.pullPolicy }}
          env:
          - name: RELAYCXN
            valueFrom:
              secretKeyRef:
                name: relaycxn
                key: cxn
          args: ["-L","latavola:8000/http:latavola", "-L","pizzaboyz:8000/http:pizzaboyz", "-L","sidepizza:8000/http:sidepizza", "-x","'$(RELAYCXN)'"] 
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
