name: Master CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Build Windows 10 - x64
      run: dotnet msbuild /t:Package /p:WindowsOnly=false /p:RuntimeIdentifier=win10-x64 /p:Configuration=Release /p:TargetFramework=netcoreapp3.1 /p:VersionSuffix=rel
    - name: Build macOS - x64
      run: dotnet msbuild /t:Package /p:WindowsOnly=false /p:RuntimeIdentifier=osx-x64 /p:Configuration=Release /p:TargetFramework=netcoreapp3.1 /p:VersionSuffix=rel
    - name: Build Ubuntu 18 - x64
      run: dotnet msbuild /t:Package /p:WindowsOnly=false /p:RuntimeIdentifier=ubuntu.18.04-x64 /p:Configuration=Release /p:TargetFramework=netcoreapp3.1 /p:VersionSuffix=rel
    - name: Build Debian 10 - x64
      run: dotnet msbuild /t:Package /p:WindowsOnly=false /p:RuntimeIdentifier=debian.10-x64 /p:Configuration=Release /p:TargetFramework=netcoreapp3.1 /p:VersionSuffix=rel
    
    - name: Test
      run: dotnet test /p:RuntimeIdentifier=ubuntu-x64 /p:Configuration=Debug
    
    - uses: actions/upload-artifact@v2
      with:
        name: XBuild
        path: artifacts/build/netcoreapp3.1
