name: CI Ubuntu x64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet msbuild /t:Package /p:Configuration=Release /p:TargetFramework=netcoreapp3.0 /p:VersionSuffix=rel
    - name: Test
      run: dotnet test /p:RuntimeIdentifier=ubuntu-x64 /p:Configuration=Debug
    
    - uses: actions/upload-artifact@v2
      with:
        name: XBuild
        path: artifacts/build/netcoreapp3.0
